### ISSUE TITLE
SRT files - quick questions

### ISSUE THREAD

**Issue by Morrizzzzz** [elpaco-escience/scikit-talk#40]
Back in the day (before streaming) I used .srt files for subtitles of movies/ series etc. Is that format still used? And how useful might this be in this project?

Maurice

**Comment by mdingemanse** [comment]
SRT is still a popular format for movie subtitles. One similarity with our kind of [minimum viable format](https://aclanthology.org/2022.lrec-1.126/) is that it includes timing information. A difference is that it doesn't do speaker identification. Probably because of that, no language corpora that we are aware of come in this kind of format, and it is not expressive enough to serve as an intermediary format. However, it could be a good starting point to learn about time-aligned linguitsic annotations.

**Comment by bvreede** [comment]
Would it be a good idea to consider adding it to the import types? This may open up sktalk for use by a whole different group of users?

**Comment by liesenf** [comment]
Yes, good to keep tabs on but low priority because .srt is rarely used in scientific work on conversation/speech.

**Comment by mdingemanse** [comment]
Afterthought: also worth noting that SRT has very different needs. For instance, subtitles don't need subsecond precision, and typically need to be on screen for minimally 1sec (e.g. [here](https://auteursbond.nl/wp-content/uploads/2020/01/Modelrichtlijnen-Nederland-Engelse-vertaling-002.pdf)); many utterances in conversational speech are much shorter than that (see Figure 7L in [same LREC paper](https://aclanthology.org/2022.lrec-1.126/)).
