### ISSUE TITLE
defining utterance context

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/scikit-talk#42]
In defining the context of an utterance U, we can use a time window: say, 10 seconds prior to U's begin, and 10 seconds after U's end.

We need to define what utterances before and after U would be a part of its context.

In this situation, there are several utterances that fall partly or entirely in the context window of U:
<img width="1520" alt="Screenshot 2023-11-10 at 14 59 59" src="https://github.com/elpaco-escience/scikit-talk/assets/5747405/41bb9635-e9f6-4c94-a7a5-3b52dfd42cd6">
The case for the green utterances, `d`, `e`, `f`, and `g`, is easy to make. The yellow ones are harder.

In discussion with @liesenf and @aliandalopez, we agreed on including all utterances except `a` in the context of U.

@mdingemanse, please let us know if you disagree!

**Comment by bvreede** [comment]
Also, if `d` ends before the context window starts, it would be out.
Or would you prefer to include it, as `b` and `c` are part of the context?

<img width="1503" alt="Screenshot 2023-11-10 at 15 13 44" src="https://github.com/elpaco-escience/scikit-talk/assets/5747405/112ca7e3-e56d-45b2-b0ab-407094b5df1b">

**Comment by mdingemanse** [comment]
As to your second question here, oof! If b and c are included, I feel it would be misleading to leave out d, because it could easily have a trajectory that relates to b or c, and/or could influence the trajectory of e just as b and c can.

That would essentially mean that the start of the context window is deterimined by the longest annotation whose end happens to fall inside it.

While this mockup helps to visualize choice points, I would rather look at actual data to see how common or rare the different edge cases actually are, and based on that make a data driven decision
