### ISSUE TITLE
Cha parsing does not include all utterances/timings

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/scikit-talk#51]
The cha parser does not work well when utterances are split over multiple lines. E.g.:

```
*A:	&=noise after all the planning and thinking about today 0_2856
	(0.8) 2856_3792
	I realised that I forgot to bring your Conan book in aga:in→ 3792_6617
	(.) 6617_6817

```
is parsed as:

```
utterance='&=noise after all the planning and thinking about today (0.8) I realised that I forgot to bring your Conan book in aga:in→ (.)', participant='A', time=[0, 2856],
```

**Comment by mdingemanse** [comment]
On mobile so can't review code but just for clarification, I want to make sure that the projected solution

-  treats all lines as separate utterances (rather than merging them)*
- assigns them to the participant to which the first line is attributed 
- uses the timing available for the individual lines
- doesn't treat times in transcripts (0.8) as utterances

*Merging them is suboptimal because we've seen they sometimes include separately marked silences (0.8) and we'd be throwing out useful turn-level timing data. Our goal in ElPaCo is to have annotations that correspond to the speech signal as closely as possible.
